// contain action types

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const INVALID_CREDENTIALS = "INVALID_CREDENTIALS";
export const GET_HOMEPAGE_DETAILS = 'GET_HOMEPAGE_DETAILS';
export const GET_PRODUCTIONLINE_DETAILS = 'GET_PRODUCTIONLINE_DETAILS';
