// contain action types

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const INVALID_CREDENTIALS = "INVALID_CREDENTIALS";
export const GET_DASHBOARD_DETAILS_OF_FACTORY_USER = 'GET_DASHBOARD_DETAILS_OF_FACTORY_USER';
export const GET_PRODUCTIONLINE_DETAILS = 'GET_PRODUCTIONLINE_DETAILS';
export const GET_SENSOR_DETAILS = 'GET_SENSOR_DETAILS';
